# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b335e3160283ca135ff210d26b951eb6a9caf5bc9efce9163789414f2c9c6c4eee15631b5f5a550dbe6a6f3b16367ee8cd63daed622c15de22f00da4f4acb7cb

test:
  secret_key_base: 07bbd3f4534c34347735d535ae6551e52bfb854a0aa8b9f99bd914a9bfc763b1a495d8bdae19e3c2ec61e14284a0fde98f3d8755798598ff6fadf8d3e56392fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
